### ISSUE TITLE
epic: remove table `pointer`

### ISSUE THREAD

**Issue by mr-git** [evolution-gaming/kafka-journal#635]
plan is:
- [x] expose library version as a metric (#631) 
- [ ] expose new temporary metric(s) on when `pointer` table is used as fallback
- [ ] release new version and track down if fallbacks are used as source of data (not expected)
- [ ] add version monitoring across all applications to make sure, that all of them are using compatible version and expose all applications, which are not updated, yet - has to be done externally, cannot be done in library
- [ ] remove the fallbacks and release the version
- [ ] update all applications to make use of new version
- [ ] remove the `pointer` table and release new version
